### ISSUE TITLE
BitVector128 not copying consistently

### ISSUE THREAD

**Issue by craigwi** [lunet-io/markdig#408] opened 2020-03-16 22:31 UTC
Here's an odd one.  I have a .NET Framework 4.6.2 test program using markdig 0.18.3 and it worked fine.  I have a UWP app (target 18362) using the same version of markdig and it fails to recognize auto links and other things.

I have traced at least one problem down to line 79 of CharacterMap.cs:

`this.isOpeningCharacter = isOpeningCharacter;`

In the .NET program, this line copies all 4 uint values of the vector.  In the UWP version, only the first uint is copied.  That is, the x86 code generated for the copy is different.

BitVector128 was introduced in 0.18.2.  I have reverted to 0.18.1 and the problem has disappeared.

**Comment by xoofx** [comment] 2020-03-17 07:27
cc: @KrisVandermotten

**Comment by KrisVandermotten** [comment] 2020-03-18 10:18
That seems to be a bug in UWP. I would suggest that first, you make sure you are using the latest version (of Visual Studio, UWP and .NET Native). If updating to the latest version does not solve the problem, report it to Microsoft.

Reporting this to Microsoft is important, as it is highly likely that MarkDig is not the only software impacted by the bug.

In the mean time, I will try to create a workaround as soon as possible. Manually copying the four uint values should do the trick (I hope).

**Comment by craigwi** [comment] 2020-03-18 15:13
Reporting to Microsoft makes sense.  I'll need to create a small repo case first.

**Comment by MihaZupan** [comment] 2020-03-18 21:16
I can reproduce this when ingesting the NuGet package, but not if targetting a locally-built master.

**Comment by craigwi** [comment] 2020-03-18 21:33
Hi @MihaZupan, I have an inside track at Microsoft. If you are willing to share the repo, I will get it to the right team to investigate.

**Comment by MihaZupan** [comment] 2020-03-18 22:08
Testing this a bit more, this only reproduces if I target the NuGet Markdig and deploying the UWP app in Debug.

Deploying in Release / ingesting a locally built Debug/Master, I can't reproduce this.

Attaching a repro - fresh UWP app, targeting the NuGet package and code that will display True/False on the window if the parsing worked.
[Test.zip](https://github.com/lunet-io/markdig/files/4351583/Test.zip)

**Comment by craigwi** [comment] 2020-03-18 23:05
I can confirm this repro: fails on Debug, succeeds on Release.  Thanks!  I will pass this on within Microsoft.

**Comment by KrisVandermotten** [comment] 2020-03-30 15:07
@craigwi Any news from Microsoft?

**Comment by MihaZupan** [comment] 2020-03-31 05:26
Nothing yet

**Comment by craigwi** [comment] 2020-03-31 17:46
I have responses now from some of the .NET team; will report back when I hear more.

**Comment by craigwi** [comment] 2020-04-06 23:15
I am in contact with a dev in .NET who owns UWP.  The issue appears limited to Debug, x86 builds -- which happens to be what I use for my everyday debugging.  x64 builds that I have tried are fine.  I haven't tried ARM.

@MihaZupan, can you confirm that x64 works for you?

**Comment by MihaZupan** [comment] 2020-04-06 23:32
Yes, I can confirm it only reproducing in x86 mode only.

I tested it with different UWP package versions and can reproduce it with `6.2.8` and **newer**.
It does not seem to affect `6.1.12` and **older**.

**Comment by craigwi** [comment] 2020-04-06 23:50
Yes, and I too discovered the fact that it appears to be a regression after 6.1.2.

**Comment by KrisVandermotten** [comment] 2020-04-27 11:46
Does this reproduce with version 0.20.0? If not, should we close this?

(I'd still like to know what happens to the bug in UWP though.)

**Comment by craigwi** [comment] 2020-04-30 17:51
Based on the test provided by @MihaZupan, the bug does not show up using 0.20.0 on x64 or x86 , debug or release.  So assuming that was the only case hitting the bug in unsafe struct copy, then we are good to go.

**Comment by MihaZupan** [comment] 2020-04-30 18:00
In that case I think we can close the issue here. We can update the info on this issue if/when we get more info about it from UWP's side.

**Closed** 2020-04-30 18:00 UTC
Labels: bug
