### ISSUE TITLE
Enable YamlFrontMatterExtension will break the heading Hr

### ISSUE THREAD

**Issue by yishengjin1413** [lunet-io/markdig#160] opened 2017-11-02 09:47 UTC
The heading Hr will not work after enable YamlFrontMatterExtension . There is an example here:

---
| Limit identifier | Limit | Comments |
| --- | --- | --- |
| Maximum |200 |beyond 200 c |

**Comment by xoofx** [comment] 2017-11-09 08:15
Hm, I'm failing to reproduce your issue.

For example the following markdown:

```
---
property: Yaml front matter
---
# This is a heading

---

This is a paragraph
```` 
will correctly remove the frontmatter and output a hr.

The YamlFrontMatter extension expect the document to start with a leading `---`. It is not intended to be used if you don't expect a YamlFrontMatter... or am I missing something?

**Comment by yishengjin1413** [comment] 2017-11-14 02:36
@xoofx , the issue is when the whole markdown is :

```
---
This is a paragraph
```

Expect it's rendered to HR + paragraph, actually it's  empty, since it rendered as YamlFronMatter.

**Comment by xoofx** [comment] 2017-11-18 09:55
Fixed by commit fbdb8cf

**Closed by xoofx** 2017-11-18 09:55 UTC
Labels: bug
